/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package soundcloud;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ali Arshad
 */
public class UserHome extends javax.swing.JFrame {

    /**
     * Creates new form UserHome
     */
    public UserHome() {
        initComponents();
        EdPanel.setVisible(false);
    }
    
    private void setLabelColor(JPanel jPanel){
        jPanel.setBackground(Color.ORANGE);
    }
    
    private void resetLabelColor(JPanel jPanel){
        jPanel.setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        Left = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TrendingListPanel = new javax.swing.JPanel();
        TrListLabel = new javax.swing.JLabel();
        BrSongPanel = new javax.swing.JPanel();
        BrSongLabel = new javax.swing.JLabel();
        BrAlbumPanel = new javax.swing.JPanel();
        BrAlbumLabel = new javax.swing.JLabel();
        EditPanel = new javax.swing.JPanel();
        EditLabel = new javax.swing.JLabel();
        Right = new javax.swing.JPanel();
        EdPanel = new javax.swing.JPanel();
        EdLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        NameEdText = new javax.swing.JTextField();
        PassLabel = new javax.swing.JLabel();
        PassEdText = new javax.swing.JPasswordField();
        MobileLabel = new javax.swing.JLabel();
        MobileEdText = new javax.swing.JTextField();
        UpdateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        Main.setBackground(new java.awt.Color(255, 255, 255));

        Left.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soundcloud/index.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        TrendingListPanel.setBackground(new java.awt.Color(255, 255, 255));
        TrendingListPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TrendingListPanelMouseClicked(evt);
            }
        });

        TrListLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TrListLabel.setForeground(new java.awt.Color(255, 153, 0));
        TrListLabel.setText("             Trending Songs");

        javax.swing.GroupLayout TrendingListPanelLayout = new javax.swing.GroupLayout(TrendingListPanel);
        TrendingListPanel.setLayout(TrendingListPanelLayout);
        TrendingListPanelLayout.setHorizontalGroup(
            TrendingListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TrListLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TrendingListPanelLayout.setVerticalGroup(
            TrendingListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TrendingListPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TrListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BrSongPanel.setBackground(new java.awt.Color(255, 255, 255));
        BrSongPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BrSongPanelMouseClicked(evt);
            }
        });

        BrSongLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BrSongLabel.setForeground(new java.awt.Color(255, 153, 51));
        BrSongLabel.setText("             Browse by Song");

        javax.swing.GroupLayout BrSongPanelLayout = new javax.swing.GroupLayout(BrSongPanel);
        BrSongPanel.setLayout(BrSongPanelLayout);
        BrSongPanelLayout.setHorizontalGroup(
            BrSongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BrSongLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BrSongPanelLayout.setVerticalGroup(
            BrSongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BrSongPanelLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(BrSongLabel)
                .addContainerGap())
        );

        BrAlbumPanel.setBackground(new java.awt.Color(255, 255, 255));
        BrAlbumPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BrAlbumPanelMouseClicked(evt);
            }
        });

        BrAlbumLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BrAlbumLabel.setForeground(new java.awt.Color(255, 153, 0));
        BrAlbumLabel.setText("            Browse by Album");

        javax.swing.GroupLayout BrAlbumPanelLayout = new javax.swing.GroupLayout(BrAlbumPanel);
        BrAlbumPanel.setLayout(BrAlbumPanelLayout);
        BrAlbumPanelLayout.setHorizontalGroup(
            BrAlbumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BrAlbumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BrAlbumPanelLayout.setVerticalGroup(
            BrAlbumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BrAlbumPanelLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(BrAlbumLabel)
                .addContainerGap())
        );

        EditPanel.setBackground(new java.awt.Color(255, 255, 255));
        EditPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditPanelMouseClicked(evt);
            }
        });

        EditLabel.setBackground(new java.awt.Color(255, 255, 255));
        EditLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EditLabel.setForeground(new java.awt.Color(255, 153, 0));
        EditLabel.setText("                Edit Details");

        javax.swing.GroupLayout EditPanelLayout = new javax.swing.GroupLayout(EditPanel);
        EditPanel.setLayout(EditPanelLayout);
        EditPanelLayout.setHorizontalGroup(
            EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EditLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        EditPanelLayout.setVerticalGroup(
            EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditPanelLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(EditLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TrendingListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BrSongPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BrAlbumPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(LeftLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
            .addComponent(EditPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TrendingListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BrSongPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BrAlbumPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        Right.setBackground(new java.awt.Color(255, 255, 255));

        EdPanel.setBackground(new java.awt.Color(255, 255, 255));

        EdLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        EdLabel.setForeground(new java.awt.Color(255, 153, 0));
        EdLabel.setText("Edit Details");

        NameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameLabel.setText("Name");

        PassLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PassLabel.setText("Password");

        MobileLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MobileLabel.setText("Mobile");

        UpdateButton.setBackground(new java.awt.Color(255, 255, 255));
        UpdateButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EdPanelLayout = new javax.swing.GroupLayout(EdPanel);
        EdPanel.setLayout(EdPanelLayout);
        EdPanelLayout.setHorizontalGroup(
            EdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EdPanelLayout.createSequentialGroup()
                .addGroup(EdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EdPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(EdLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EdPanelLayout.createSequentialGroup()
                        .addContainerGap(43, Short.MAX_VALUE)
                        .addGroup(EdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameLabel)
                            .addComponent(PassLabel)
                            .addComponent(MobileLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(EdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpdateButton)
                            .addGroup(EdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(PassEdText)
                                .addComponent(NameEdText)
                                .addComponent(MobileEdText, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        EdPanelLayout.setVerticalGroup(
            EdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EdPanelLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(EdLabel)
                .addGap(48, 48, 48)
                .addGroup(EdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(NameEdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(EdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PassLabel)
                    .addComponent(PassEdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(EdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MobileLabel)
                    .addComponent(MobileEdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(UpdateButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EdPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        RightLayout.setVerticalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EdPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addComponent(Left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Right, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Right, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TrendingListPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrendingListPanelMouseClicked
        // TODO add your handling code here:
        setLabelColor(TrendingListPanel);
        resetLabelColor(BrSongPanel);
        resetLabelColor(BrAlbumPanel);
        resetLabelColor(EditPanel);
        EdPanel.setVisible(false);
    }//GEN-LAST:event_TrendingListPanelMouseClicked

    private void BrSongPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BrSongPanelMouseClicked
        // TODO add your handling code here:
        setLabelColor(BrSongPanel);
        resetLabelColor(TrendingListPanel);
        resetLabelColor(BrAlbumPanel);
        resetLabelColor(EditPanel);
        EdPanel.setVisible(false);
    }//GEN-LAST:event_BrSongPanelMouseClicked

    private void BrAlbumPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BrAlbumPanelMouseClicked
        // TODO add your handling code here:
        setLabelColor(BrAlbumPanel);
        resetLabelColor(TrendingListPanel);
        resetLabelColor(BrSongPanel);
        resetLabelColor(EditPanel);
        EdPanel.setVisible(false);
    }//GEN-LAST:event_BrAlbumPanelMouseClicked

    private void EditPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditPanelMouseClicked
        // TODO add your handling code here:
        setLabelColor(EditPanel);
        resetLabelColor(TrendingListPanel);
        resetLabelColor(BrAlbumPanel);
        resetLabelColor(BrSongPanel);
        EdPanel.setVisible(true);
        NameEdText.setText(SoundCloud.u.name);
        PassEdText.setText(SoundCloud.u.password);
        MobileEdText.setText(SoundCloud.u.mobile_number);
    }//GEN-LAST:event_EditPanelMouseClicked

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        String Name = NameEdText.getText().toString();
        char[] p = PassEdText.getPassword();
        String pass = new String(p);
        String mob = MobileEdText.getText().toString();
        SoundCloud.u.setName(Name);
        SoundCloud.u.setPassword(pass);
        SoundCloud.u.setNum(mob);
        DBConnection db = DBConnection.getInstance();
        boolean flag = db.updateUser(SoundCloud.u);
        if (flag == true)
        {
            JOptionPane.showMessageDialog(this, "User updated Succesfully");
            resetLabelColor(EditPanel);
            EdPanel.setVisible(false);
        }
        else
            JOptionPane.showMessageDialog(this, "User not Updated");
    }//GEN-LAST:event_UpdateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new UserHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BrAlbumLabel;
    private javax.swing.JPanel BrAlbumPanel;
    private javax.swing.JLabel BrSongLabel;
    private javax.swing.JPanel BrSongPanel;
    private javax.swing.JLabel EdLabel;
    private javax.swing.JPanel EdPanel;
    private javax.swing.JLabel EditLabel;
    private javax.swing.JPanel EditPanel;
    private javax.swing.JPanel Left;
    private javax.swing.JPanel Main;
    private javax.swing.JTextField MobileEdText;
    private javax.swing.JLabel MobileLabel;
    private javax.swing.JTextField NameEdText;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JPasswordField PassEdText;
    private javax.swing.JLabel PassLabel;
    private javax.swing.JPanel Right;
    private javax.swing.JLabel TrListLabel;
    private javax.swing.JPanel TrendingListPanel;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
